"""
Entity models for Milvus partition operations.

This module defines Pydantic models for representing Milvus partition
states, statistics, and metadata in a strongly-typed manner.

This module uses Pydantic v2 compatible model definitions.
"""

from enum import Enum
from typing import Dict, List, Optional, Any, Union
from datetime import datetime
from pydantic import BaseModel, Field


class PartitionLoadState(str, Enum):
    """
    Enumeration of possible states for a partition's memory load status.
    
    This provides a clear, explicit representation of whether a partition is
    currently loaded into Milvus's memory for querying, unloaded, or in a
    transitional state.
    """
    UNLOADED = "Unloaded"
    LOADING = "Loading"
    LOADED = "Loaded"
    FAILED = "Failed"


class PartitionState(str, Enum):
    """
    Enumeration of possible lifecycle states for a partition.
    
    This is intended for tracking partition lifecycle management including
    creation, availability, and deletion states.
    """
    CREATING = "Creating"
    AVAILABLE = "Available"
    DROPPING = "Dropping"
    DELETED = "Deleted"
    FAILED = "Failed"


class PartitionDescription(BaseModel):
    """
    A Pydantic model that provides a detailed description of a Milvus partition.
    
    This model encapsulates all the critical metadata about a partition, including
    its name, ID, collection association, creation time, and current state.

    Attributes:
        name: The unique name of the partition within its collection.
        partition_id: The unique identifier for the partition, assigned by Milvus.
        collection_name: The name of the collection this partition belongs to.
        collection_id: The logical identifier of the collection this partition belongs to.
        created_at: The timestamp when the partition was created.
        state: The lifecycle state of the partition (e.g., `AVAILABLE`).
        load_state: The current memory load state of the partition (e.g., `LOADED`).
        created_at_is_synthetic: A boolean flag that is `True` if the `created_at`
                                timestamp was generated by the client because it
                                was not available from the server.
    """
    name: str = Field(..., description="The unique name of the partition within its collection.")
    partition_id: str = Field(..., description="The unique identifier for the partition.")
    collection_name: str = Field(..., description="The name of the collection this partition belongs to.")
    collection_id: str = Field(..., description="The logical identifier of the collection this partition belongs to.")
    created_at: datetime = Field(..., description="The timestamp of when the partition was created.")
    state: PartitionState = Field(PartitionState.AVAILABLE, description="The current lifecycle state of the partition.")
    load_state: PartitionLoadState = Field(PartitionLoadState.UNLOADED, description="The current memory load state of the partition.")
    created_at_is_synthetic: bool = Field(False, description="True if the creation timestamp was synthesized by the client.")

    model_config = {
        "arbitrary_types_allowed": True
    }


class PartitionStats(BaseModel):
    """
    A Pydantic model that provides detailed statistics for a Milvus partition.
    
    This model aggregates various metrics about a partition, such as its size,
    number of entities, and details about segments. It is essential for 
    monitoring, capacity planning, and performance tuning.

    Attributes:
        name: The name of the partition.
        partition_id: The unique identifier of the partition.
        collection_name: The name of the collection this partition belongs to.
        collection_id: The logical identifier of the collection this partition belongs to.
        created_at: The timestamp when the partition was created.
        row_count: The total number of entities (vectors) in the partition.
        memory_size: The total estimated memory size of the partition in bytes.
        disk_size: The total estimated disk size of the partition in bytes.
        index_size: The total estimated size of all indexes in the partition, in bytes.
        num_segments: The total number of segments within this partition.
        segments: A list of segment information objects with details about each segment.
    """
    name: str = Field(..., description="The name of the partition.")
    partition_id: str = Field(..., description="The logical identifier of the partition.")
    collection_name: str = Field(..., description="The name of the collection this partition belongs to.")
    collection_id: str = Field(..., description="The logical identifier of the collection this partition belongs to.")
    created_at: datetime = Field(..., description="The timestamp of when the partition was created.")
    row_count: int = Field(0, description="The total number of entities in the partition.")
    memory_size: int = Field(0, description="The total memory size of the partition in bytes.")
    disk_size: int = Field(0, description="The total disk size of the partition in bytes.")
    index_size: int = Field(0, description="The total size of all indexes in the partition, in bytes.")
    num_segments: int = Field(0, description="The total number of segments in the partition.")
    segments: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="A list of detailed information about each segment."
    )
    
    @property
    def total_size(self) -> int:
        """Get the total size of the partition (memory + disk + index)."""
        return self.memory_size + self.disk_size + self.index_size
    
    @property
    def is_empty(self) -> bool:
        """Check if the partition is empty (no entities)."""
        return self.row_count == 0
    
    @property
    def average_segment_size(self) -> float:
        """Get the average size of segments in the partition."""
        if self.num_segments == 0:
            return 0.0
        return self.total_size / self.num_segments
    
    @classmethod
    def from_milvus_response(cls, partition_name: str, collection_name: str, stats: Dict[str, Any]) -> "PartitionStats":
        """
        Create a PartitionStats object from a Milvus response.
        
        This class method serves as a factory to parse the raw dictionary returned
        by the Milvus SDK into a structured, validated `PartitionStats` object.

        Args:
            partition_name: The name of the partition.
            collection_name: The name of the collection this partition belongs to.
            stats: The raw statistics dictionary from the Milvus SDK.
            
        Returns:
            A populated `PartitionStats` object.
        """
        # Extract basic stats
        row_count = stats.get("row_count", 0)
        
        # Extract partition and collection IDs
        partition_id = stats.get("partition_id", partition_name)
        collection_id = stats.get("collection_id", collection_name)
        
        # Handle created_at with type stability
        created_at = cls._parse_timestamp(stats.get("created_utc", datetime.now().timestamp()))
        
        # Calculate sizes
        memory_size = stats.get("memory_size", 0)
        disk_size = stats.get("disk_size", 0)
        index_size = stats.get("index_size", 0)
        
        # Process segments if available
        segments = stats.get("segments", [])
        num_segments = len(segments)
        
        # Update size totals if segments are available
        if segments:
            for segment in segments:
                memory_size += segment.get("memory_size", 0)
                disk_size += segment.get("disk_size", 0)
                index_size += segment.get("index_size", 0)
        
        return cls(
            name=partition_name,
            partition_id=partition_id,
            collection_name=collection_name,
            collection_id=collection_id,
            created_at=created_at,
            row_count=row_count,
            memory_size=memory_size,
            disk_size=disk_size,
            index_size=index_size,
            num_segments=num_segments,
            segments=segments
        )
    
    @staticmethod
    def _parse_timestamp(timestamp_value: Union[float, int, str]) -> datetime:
        """
        Safely parse a timestamp value to a datetime object.
        
        This helper ensures type stability when working with timestamps from
        external sources that might be inconsistently typed.
        
        Args:
            timestamp_value: A timestamp value as float, int, or string
            
        Returns:
            A datetime object representing the timestamp, or current time if parsing fails
        """
        try:
            if isinstance(timestamp_value, (int, float)):
                return datetime.fromtimestamp(float(timestamp_value))
            elif isinstance(timestamp_value, str):
                return datetime.fromtimestamp(float(timestamp_value))
            else:
                return datetime.now()
        except (ValueError, TypeError):
            return datetime.now()


class LoadProgress(BaseModel):
    """
    A Pydantic model representing the progress of a partition loading operation.
    
    This model provides real-time feedback on the status of loading a partition
    into memory, which can be a long-running operation for large partitions.

    Attributes:
        partition_name: The name of the partition being loaded.
        collection_name: The name of the collection this partition belongs to.
        state: The current `PartitionLoadState` of the operation (e.g., `LOADING`, `LOADED`).
        progress: The loading progress as a float between 0.0 and 1.0.
        loaded_segments: The number of segments that have been successfully loaded.
        total_segments: The total number of segments that need to be loaded.
        error_message: If the loading fails, this field contains the error message.
    """
    partition_name: str = Field(..., description="The name of the partition being loaded.")
    collection_name: str = Field(..., description="The name of the collection this partition belongs to.")
    state: PartitionLoadState = Field(..., description="The current loading state of the partition.")
    progress: float = Field(..., description="The loading progress, from 0.0 to 1.0.")
    loaded_segments: int = Field(0, description="The number of segments successfully loaded.")
    total_segments: int = Field(0, description="The total number of segments to be loaded.")
    error_message: Optional[str] = Field(None, description="Contains an error message if the loading process failed.")
    
    @property
    def is_complete(self) -> bool:
        """Check if loading is complete (either successful or failed)."""
        return self.state == PartitionLoadState.LOADED or self.state == PartitionLoadState.FAILED
    
    @property
    def is_successful(self) -> bool:
        """Check if loading was successful."""
        return self.state == PartitionLoadState.LOADED
    
    @property
    def is_failed(self) -> bool:
        """Check if loading failed."""
        return self.state == PartitionLoadState.FAILED
    
    @property
    def percentage_complete(self) -> str:
        """Get the progress as a percentage string."""
        return f"{self.progress * 100:.1f}%"
    
    @classmethod
    def from_milvus_response(cls, partition_name: str, collection_name: str, progress: Dict[str, Any]) -> "LoadProgress":
        """
        Create a LoadProgress object from a Milvus response.
        
        This class method serves as a factory to parse the raw dictionary returned
        by the Milvus SDK's progress API into a structured `LoadProgress` object.

        Args:
            partition_name: The name of the partition.
            collection_name: The name of the collection this partition belongs to.
            progress: The raw progress dictionary from the Milvus SDK.
            
        Returns:
            A populated `LoadProgress` object.
        """
        # Extract progress information
        loading_progress = progress.get("loading_progress", "0%")
        
        # Convert percentage string to float
        try:
            if isinstance(loading_progress, str) and loading_progress.endswith("%"):
                progress_value = float(loading_progress.rstrip("%")) / 100.0
            else:
                progress_value = float(loading_progress)
        except (ValueError, TypeError):
            progress_value = 0.0
        
        # Determine state based on progress
        if progress_value >= 1.0:
            state = PartitionLoadState.LOADED
        elif progress_value > 0.0:
            state = PartitionLoadState.LOADING
        else:
            state = PartitionLoadState.UNLOADED
        
        # Extract segment information if available
        loaded_segments = progress.get("loaded_segments", 0)
        total_segments = progress.get("total_segments", 0)
        
        return cls(
            partition_name=partition_name,
            collection_name=collection_name,
            state=state,
            progress=progress_value,
            loaded_segments=loaded_segments,
            total_segments=total_segments,
            error_message=progress.get("error")
        )